module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.15

require (
	github.com/fatih/color v1.10.0 // indirect
	github.com/google/go-jsonnet v0.17.1-0.20210101181740-31d71aaccda6 // cmd/jsonnetfmt
	golang.org/x/sys v0.0.0-20210112091331-59c308dcf3cc // indirect
)
