module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.15

require (
	github.com/fatih/color v1.10.0 // indirect
	github.com/google/go-jsonnet v0.17.0 // cmd/jsonnet-lint
	golang.org/x/sys v0.0.0-20201119102817-f84b799fce68 // indirect
)
