# type: s3
# config:
#   bucket: thanos
#   endpoint: minio.monitoring.svc.cluster.local:9000
#   insecure: true
#   access_key: minio
#   secret_key: minio123

apiVersion: v1
kind: Secret
metadata:
  name: thanos-objectstorage
  namespace: monitoring
type: Opaque
data:
  thanos.yaml: dHlwZTogczMKY29uZmlnOgogIGJ1Y2tldDogdGhhbm9zCiAgZW5kcG9pbnQ6IG1pbmlvLm1vbml0b3Jpbmcuc3ZjLmNsdXN0ZXIubG9jYWw6OTAwMAogIGluc2VjdXJlOiB0cnVlCiAgYWNjZXNzX2tleTogbWluaW8KICBzZWNyZXRfa2V5OiBtaW5pbzEyMwo=
