jobs:
  build:
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    docker:
      - image: quay.io/coreos/jsonnet-ci
    steps:
      - checkout
      - run: make --always-make vendor generate
      - run: git diff --exit-code
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
