apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: database-compactor
    app.kubernetes.io/instance: thanos-compact-1
    app.kubernetes.io/name: thanos-compact
    app.kubernetes.io/version: v0.26.0
    compact.thanos.io/shard: shard-1
  name: thanos-compact-1
  namespace: thanos
spec:
  clusterIP: None
  ports:
  - name: http
    port: 10902
    targetPort: 10902
  selector:
    app.kubernetes.io/component: database-compactor
    app.kubernetes.io/instance: thanos-compact-1
    app.kubernetes.io/name: thanos-compact
    compact.thanos.io/shard: shard-1
