apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: thanos-ruler
  namespace: monitoring
spec:
  endpoints:
  - port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos-ruler
