apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/component: object-store-bucket-replicate
    app.kubernetes.io/instance: thanos-bucket-replicate
    app.kubernetes.io/name: thanos-bucket-replicate
    app.kubernetes.io/version: v0.29.0
  name: thanos-bucket-replicate
  namespace: thanos
